"""Tables revision

Revision ID: 03288aadf492
Revises: 3fa48b9e4f10
Create Date: 2024-04-03 17:52:55.087852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03288aadf492'
down_revision = '3fa48b9e4f10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
