"""Tables revision

Revision ID: 199a88b6d957
Revises: dc959493a8de
Create Date: 2024-04-03 08:59:28.828926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199a88b6d957'
down_revision = 'dc959493a8de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
