"""Tables revision

Revision ID: 3667e1530924
Revises: 2671e058fb17
Create Date: 2024-04-03 17:53:43.793617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3667e1530924'
down_revision = '2671e058fb17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
