"""Tables revision

Revision ID: 3fa48b9e4f10
Revises: 5502db594300
Create Date: 2024-04-03 17:52:39.005925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa48b9e4f10'
down_revision = '5502db594300'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
