"""Tables revision

Revision ID: 7def42edb961
Revises: d9d0fd4b0ba7
Create Date: 2024-04-03 09:26:21.606648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7def42edb961'
down_revision = 'd9d0fd4b0ba7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
