"""Tables revision

Revision ID: 97910580b813
Revises: c4184183a085
Create Date: 2024-04-03 17:53:22.280026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97910580b813'
down_revision = 'c4184183a085'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
