"""Tables revision

Revision ID: a29114c885a7
Revises: 563647654091
Create Date: 2024-04-03 17:52:08.809994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29114c885a7'
down_revision = '563647654091'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
