"""Tables revision

Revision ID: a4bfeb5d98c3
Revises: 3667e1530924
Create Date: 2024-04-03 17:53:56.681369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bfeb5d98c3'
down_revision = '3667e1530924'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
