"""Tables revision

Revision ID: d9d0fd4b0ba7
Revises: 199a88b6d957
Create Date: 2024-04-03 09:14:39.820994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d0fd4b0ba7'
down_revision = '199a88b6d957'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
