"""Tables revision

Revision ID: dc959493a8de
Revises: a9c79cda550a
Create Date: 2024-04-03 08:45:40.500355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc959493a8de'
down_revision = 'a9c79cda550a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
