"""Tables revision

Revision ID: df9a27d56860
Revises: a4bfeb5d98c3
Create Date: 2024-04-03 17:54:08.389321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9a27d56860'
down_revision = 'a4bfeb5d98c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
